Add simple Makefile for Poisson demo. Currently breaks with
main.o: In function `Test_runtime_rounding_modes':
/home/logg/scratch/lib/fenics-dev/include/CGAL/Interval_nt.h:157: undefined reference to `CGAL::assertion_fail(char const*, char const*, int, char const*)'