propagate use of XTENSOR_USE_XSIMD
If a dolfinx build is configured with XTENSOR_USE_XSIMD to enable
xtensor to take advantage of XSIMD acceleration, then xsimd gets
written into the symbol table for libdolfinx.so (in
mesh::locate_entities and mesh::locate_entities_boundary)

Then at run time XTENSOR_USE_XSIMD would need to be added manually to
camke or CXXFLAGS configuration, otherwise the signature for
locate_entities will be discrepant, causing build errors, e.g.
  undefined reference to `dolfinx::mesh::locate_entities_boundary`

This patch propagates the use of XTENSOR_USE_XSIMD into installed
dolfinx configuratin files (DOLFINXTargets.cmake and dolfinx.pc) to
facilitate a consistent xtensor (xsimd) configuration.